import { writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { readPackageVersion } from './release/version.mjs';

/**
 * Generate `src/environments/version.ts` from package.json's semantic version.
 *
 * This is the single source of truth for the version shown in the UI. It is the
 * same value the ESP32 release pipeline stamps into version.json / latest.json,
 * so the running app and the released bundle always report the same version.
 *
 * Wired into the start/build/release npm scripts so it stays in sync
 * automatically. We generate a tiny constant instead of importing package.json
 * directly, because bundlers inline the *entire* package.json (dependency list
 * and all) into the client chunk — this ships only the version string.
 */
const projectRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const version = readPackageVersion(projectRoot);

const outPath = join(projectRoot, 'src', 'environments', 'version.ts');
const contents =
  `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.\n` +
  `// Source of truth: package.json "version". Regenerate: npm run gen:version\n` +
  `export const APP_VERSION = '${version}';\n`;

writeFileSync(outPath, contents);
console.log(`  version.ts -> ${version}`);
